# Generated by Django 3.0.3 on 2020-04-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, unique=True)),
                ('restaurant_address', models.CharField(max_length=200)),
                ('restaurant_street_number', models.CharField(max_length=10)),
                ('restaurant_city', models.CharField(max_length=200)),
                ('restaurant_cuisine_type', models.CharField(choices=[('Traditional / polish', 'Traditional / polish'), ('Italian', 'Italian'), ('American / burger', 'American / burger'), ('Indian', 'Indian'), ('Thai', 'Thai'), ('Chinese', 'Chinese'), ('Japanese / sushi', 'Japanese / sushi'), ('Other', 'Other')], max_length=50)),
                ('restaurant_category', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Fast-food', 'Fast-food'), ('Pub', 'Pub')], max_length=25)),
                ('restaurant_website_link', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review_grade', models.IntegerField(choices=[(1, '1 - Not satisfied'), (2, '2 - Almost satisfied'), (3, '3 - Satisfied'), (4, '4 - Very satisfied'), (5, '5 - Exceptionally satisfied')], default=None)),
                ('user_review_comment', models.CharField(max_length=1500)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
